import type { Metadata } from "next";
import "./ui/globals.css";
import { lusitana } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Map of Couly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
      </head>
      <body className={`${lusitana.className}`}>
        {children}
      </body>
    </html>
  );
}
